export type ItineraryCategory =
  | "flight"
  | "transit"
  | "hotel"
  | "food"
  | "photo"
  | "cafe"
  | "shopping"
  | "rest";

export type ItineraryItem = {
  id: string;
  startTime: string;
  endTime?: string;
  title: string;
  category: ItineraryCategory;
  location: string;
  address: string;
  naverQuery: string;
  note: string;
  details: string[];
  tips: string[];
  image?: string;
};

export type ItineraryDay = {
  id: string;
  label: string;
  date: string;
  tabDate: string;
  weekday: string;
  title: string;
  area: string;
  theme: string;
  items: ItineraryItem[];
};

export const itineraryStorageKey = "seoul-travel-hub-itinerary-v2";

const hotelRoomImage =
  "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=900&auto=format&fit=crop";
const airportRailroadImage = "/images/arex-train.jpg";
const kaohsiungAirportImage =
  "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=900&auto=format&fit=crop";

export const categoryLabels: Record<ItineraryCategory, string> = {
  flight: "航班",
  transit: "交通",
  hotel: "飯店",
  food: "餐飲",
  photo: "拍照",
  cafe: "咖啡",
  shopping: "購物",
  rest: "休息",
};

export const defaultItineraryDays: ItineraryDay[] = [
  {
    id: "day-1",
    label: "DAY 1",
    date: "2026.10.10",
    tabDate: "10.10",
    weekday: "Sat",
    title: "抵達首爾",
    area: "弘大",
    theme: "高雄 → 金浦機場 → 弘大 → 晚餐 → 夜間散步",
    items: [
      {
        id: "d1-flight-khh",
        startTime: "15:55",
        title: "高雄小港機場出發",
        category: "flight",
        location: "KHH → GMP",
        address: "高雄國際機場",
        naverQuery: "高雄國際機場",
        note: "Tigerair Taiwan IT662",
        details: ["15:55 起飛", "目的地為金浦機場 GMP", "出發前先確認護照與登機資訊"],
        tips: ["航班日前一天先完成線上報到。", "登機證、護照、韓國入境資料放在同一個收納夾。"],
        image: kaohsiungAirportImage,
      },
      {
        id: "d1-arrive-gmp",
        startTime: "19:45",
        title: "抵達金浦機場",
        category: "transit",
        location: "Gimpo Airport",
        address: "김포국제공항",
        naverQuery: "김포국제공항",
        note: "入境、領行李、交通卡",
        details: ["19:45 抵達", "完成入境檢查", "領行李後準備前往弘大"],
        tips: ["機場先確認 T-money 或交通卡餘額。", "若同行朋友分散，約在到達大廳集合。"],
        image:
          "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d1-arex-hongdae",
        startTime: "20:15",
        endTime: "21:00",
        title: "前往飯店",
        category: "transit",
        location: "機場鐵道 AREX",
        address: "홍대입구역",
        naverQuery: "홍대입구역",
        note: "抵達弘大入口站",
        details: ["搭乘機場鐵道 AREX", "從金浦機場前往弘大入口站", "抵達後先前往飯店"],
        tips: ["晚間拖行李移動，路線以電梯出口優先。", "先截圖住宿地址，避免網路不穩。"],
        image: airportRailroadImage,
      },
      {
        id: "d1-check-in",
        startTime: "21:00",
        endTime: "21:30",
        title: "辦理入住",
        category: "hotel",
        location: "弘大住宿",
        address: "弘大 Hongdae",
        naverQuery: "홍대입구역 호텔",
        note: "放置行李、整理隨身物品、領取房卡",
        details: ["辦理入住", "放置行李", "整理隨身物品與票券"],
        tips: ["確認隔天出門要帶的東西。", "先把充電線、行動電源、護照固定位置。"],
        image:
          "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d1-dinner",
        startTime: "21:30",
        endTime: "22:30",
        title: "弘大晚餐",
        category: "food",
        location: "弘大商圈",
        address: "홍대거리",
        naverQuery: "홍대 맛집",
        note: "神仙雪濃湯、辣炒年糕、橋村炸雞或 Issac Toast",
        details: ["第一晚視體力選附近餐廳", "以不用排太久、離住宿近為優先", "若太晚可改便利商店簡單吃"],
        tips: ["第一晚不要排太硬，重點是安全抵達與休息。", "若餐廳已休息，直接找弘大商圈附近營業店。"],
        image:
          "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d1-hongdae-night",
        startTime: "22:30",
        endTime: "23:30",
        title: "弘大夜間散步",
        category: "photo",
        location: "弘大商圈",
        address: "홍대거리",
        naverQuery: "홍대거리",
        note: "街頭藝人、夜間街景、第一晚首爾氛圍",
        details: ["弘大商圈散步", "街頭藝人", "夜間街景拍照"],
        tips: ["第一晚拍照以輕鬆紀錄為主。", "注意手機電量與人潮中的隨身物。"],
        image:
          "https://images.unsplash.com/photo-1538485399081-7191377e8241?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d1-rest",
        startTime: "23:30",
        title: "返回飯店休息",
        category: "hotel",
        location: "弘大飯店",
        address: "弘大 Hongdae",
        naverQuery: "홍대입구역 호텔",
        note: "整理隔天物品並休息",
        details: ["返回飯店", "充電、備份照片", "確認 Day 2 出門時間"],
        tips: ["第一天不要熬太晚，Day 2 會是拍照重點日。"],
        image: hotelRoomImage,
      },
    ],
  },
  {
    id: "day-2",
    label: "DAY 2",
    date: "2026.10.11",
    tabDate: "10.11",
    weekday: "Sun",
    title: "首爾傳統文化日",
    area: "景福宮",
    theme: "景福宮 → 北村 → 益善洞",
    items: [
      {
        id: "d2-start",
        startTime: "09:00",
        title: "飯店出發",
        category: "hotel",
        location: "弘大飯店",
        address: "홍대입구역",
        naverQuery: "홍대입구역 호텔",
        note: "前往景福宮周邊",
        details: ["09:00 從飯店出發", "先抓交通與換乘時間", "抵達後開始傳統文化路線"],
        tips: ["若要租韓服，建議提早確認店家開門時間。"],
        image: hotelRoomImage,
      },
      {
        id: "d2-gyeongbokgung",
        startTime: "10:00",
        endTime: "12:00",
        title: "景福宮",
        category: "photo",
        location: "Gyeongbokgung Palace",
        address: "서울 종로구 사직로 161 경복궁",
        naverQuery: "경복궁",
        note: "韓服照、光化門、勤政殿",
        details: ["光化門", "勤政殿", "宮殿建築與韓服照"],
        tips: ["每週二通常休宮，請出發前再確認開放時間。", "上午光線比較柔，適合拍人物照。"],
        image:
          "https://images.unsplash.com/photo-1599571234909-29ed5d1321d6?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d2-tosokchon",
        startTime: "12:00",
        endTime: "13:30",
        title: "土俗村參雞湯",
        category: "food",
        location: "Tosokchon Samgyetang",
        address: "서울 종로구 자하문로5길 5 토속촌",
        naverQuery: "토속촌 삼계탕",
        note: "景福宮附近午餐",
        details: ["午餐安排土俗村參雞湯", "景福宮附近名店", "用餐後前往北村"],
        tips: ["熱門時段可能排隊，若人潮太多可改附近餐廳。", "用餐後補水，下午會走較多路。"],
        image:
          "https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d2-bukchon",
        startTime: "13:30",
        endTime: "16:00",
        title: "北村韓屋村",
        category: "photo",
        location: "Bukchon Hanok Village",
        address: "서울 종로구 계동길 37",
        naverQuery: "북촌한옥마을",
        note: "韓屋街景、坡道拍攝",
        details: ["韓屋街景", "坡道構圖", "傳統巷弄照片"],
        tips: ["北村是居民區，拍照時降低音量。", "坡道多，鞋子以好走為主。"],
        image:
          "https://images.unsplash.com/photo-1517154421773-0529f29ea451?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d2-cafe",
        startTime: "16:00",
        endTime: "17:00",
        title: "咖啡廳休息",
        category: "cafe",
        location: "北村 / 安國周邊",
        address: "안국역",
        naverQuery: "안국역 카페",
        note: "補充體力，整理照片",
        details: ["找附近咖啡廳休息", "整理相機與手機電量", "準備前往益善洞"],
        tips: ["這段是緩衝時間，可以依體力延長或縮短。"],
        image:
          "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d2-ikseondong",
        startTime: "17:00",
        endTime: "21:00",
        title: "益善洞",
        category: "photo",
        location: "Ikseon-dong",
        address: "서울 종로구 익선동",
        naverQuery: "익선동",
        note: "文青咖啡廳、韓屋巷弄、夜景",
        details: ["韓屋巷弄", "文青咖啡廳", "傍晚與夜間街景"],
        tips: ["巷弄小、人潮多，拍照時注意後方行人。", "傍晚到夜間的燈光變化很適合拍照。"],
        image:
          "https://images.unsplash.com/photo-1538485399081-7191377e8241?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d2-back",
        startTime: "22:00",
        title: "返回飯店",
        category: "hotel",
        location: "弘大飯店",
        address: "홍대입구역",
        naverQuery: "홍대입구역 호텔",
        note: "回飯店休息",
        details: ["返回飯店", "整理照片與隔天物品"],
        tips: ["Day 3 會走東大門與夜景路線，早點休息。"],
        image: hotelRoomImage,
      },
    ],
  },
  {
    id: "day-3",
    label: "DAY 3",
    date: "2026.10.12",
    tabDate: "10.12",
    weekday: "Mon",
    title: "首爾現代設計日",
    area: "東大門",
    theme: "DDP → 梨花洞 → 駱山公園",
    items: [
      {
        id: "d3-start",
        startTime: "09:00",
        title: "飯店出發",
        category: "hotel",
        location: "弘大飯店",
        address: "홍대입구역",
        naverQuery: "홍대입구역 호텔",
        note: "前往東大門設計廣場",
        details: ["09:00 從飯店出發", "前往 DDP 東大門設計廣場"],
        tips: ["今天建築與夜景較多，相機電量要先滿。"],
        image: hotelRoomImage,
      },
      {
        id: "d3-ddp",
        startTime: "10:00",
        endTime: "13:00",
        title: "DDP 東大門設計廣場",
        category: "photo",
        location: "Dongdaemun Design Plaza",
        address: "서울 중구 을지로 281",
        naverQuery: "동대문디자인플라자",
        note: "未來感建築、曲面建築、建築攝影",
        details: ["未來感建築", "曲面外牆", "室內外建築攝影"],
        tips: ["廣角鏡頭很適合這裡。", "若天氣太熱或下雨，可多安排室內展區。"],
        image:
          "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d3-lunch",
        startTime: "13:00",
        endTime: "15:00",
        title: "東大門午餐",
        category: "food",
        location: "東大門周邊",
        address: "동대문역사문화공원역",
        naverQuery: "동대문 맛집",
        note: "東大門周邊用餐",
        details: ["午餐與休息", "視體力調整後續路線"],
        tips: ["下午有坡道與夜景，午餐後可先補水。"],
        image:
          "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d3-ihwa",
        startTime: "15:00",
        endTime: "17:00",
        title: "梨花洞壁畫村",
        category: "photo",
        location: "Ihwa Mural Village",
        address: "서울 종로구 이화동",
        naverQuery: "이화동 벽화마을",
        note: "彩繪牆、坡道街景、文創氛圍",
        details: ["彩繪牆", "坡道街景", "文創巷弄"],
        tips: ["這區坡度明顯，行程不要排太趕。", "居民區拍照要注意音量。"],
        image:
          "https://images.unsplash.com/photo-1517154421773-0529f29ea451?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d3-naksan",
        startTime: "17:00",
        endTime: "20:00",
        title: "駱山公園",
        category: "photo",
        location: "Naksan Park",
        address: "서울 종로구 낙산길 41",
        naverQuery: "낙산공원",
        note: "首爾城牆、夜景、日落藍調時刻",
        details: ["首爾城牆", "日落", "藍調時刻夜景"],
        tips: ["傍晚風可能較大，帶薄外套。", "日落前 30 分鐘到比較好抓位置。"],
        image:
          "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d3-dongdaemun-shopping",
        startTime: "20:00",
        endTime: "22:00",
        title: "東大門商圈",
        category: "shopping",
        location: "東大門商圈",
        address: "동대문",
        naverQuery: "동대문 쇼핑",
        note: "夜間逛街與補給",
        details: ["東大門商圈", "夜間購物", "視體力調整停留時間"],
        tips: ["如果太累可直接回弘大，不要硬撐。"],
        image:
          "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d3-back",
        startTime: "22:00",
        title: "返回飯店",
        category: "hotel",
        location: "弘大飯店",
        address: "홍대입구역",
        naverQuery: "홍대입구역 호텔",
        note: "回飯店休息",
        details: ["返回飯店", "整理照片與行李"],
        tips: ["Day 4 是潮流街區，可保留體力。"],
        image: hotelRoomImage,
      },
    ],
  },
  {
    id: "day-4",
    label: "DAY 4",
    date: "2026.10.13",
    tabDate: "10.13",
    weekday: "Tue",
    title: "首爾潮流文青日",
    area: "聖水洞",
    theme: "聖水洞 → 漢南洞 → 弘大夜拍",
    items: [
      {
        id: "d4-start",
        startTime: "09:00",
        title: "飯店出發",
        category: "hotel",
        location: "弘大飯店",
        address: "홍대입구역",
        naverQuery: "홍대입구역 호텔",
        note: "前往聖水洞",
        details: ["09:00 從飯店出發", "前往聖水洞潮流街區"],
        tips: ["今天會有很多咖啡廳與品牌店，手機電量要顧好。"],
        image: hotelRoomImage,
      },
      {
        id: "d4-seongsu",
        startTime: "10:00",
        endTime: "15:00",
        title: "聖水洞",
        category: "photo",
        location: "Seongsu-dong",
        address: "서울 성동구 성수동",
        naverQuery: "성수동",
        note: "Cafe Onion、工業風街景、潮流品牌店",
        details: ["Cafe Onion", "工業風街景", "潮流品牌店", "韓國版 Brooklyn"],
        tips: ["可以先標記想去的咖啡廳，避免現場選擇太多。", "街景和店面外觀都適合拍照。"],
        image:
          "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d4-hannam",
        startTime: "15:00",
        endTime: "18:00",
        title: "漢南洞",
        category: "photo",
        location: "Hannam-dong",
        address: "서울 용산구 한남동",
        naverQuery: "한남동",
        note: "精品街區、高級咖啡廳、韓系生活感",
        details: ["精品街區", "高級咖啡廳", "韓系生活感街景"],
        tips: ["這段適合慢慢逛，不必每家店都進。", "若購物時間拉長，弘大夜拍可縮短。"],
        image:
          "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d4-hongdae-night",
        startTime: "18:00",
        endTime: "22:00",
        title: "弘大商圈",
        category: "photo",
        location: "弘大商圈",
        address: "홍대거리",
        naverQuery: "홍대거리",
        note: "街頭藝人、夜景、潮流商店；晚餐安排於弘大",
        details: ["街頭藝人", "夜景", "潮流商店", "弘大晚餐"],
        tips: ["晚餐可以跟 Day 1 沒吃到的店互補。", "街頭表演人潮多，注意隨身物。"],
        image:
          "https://images.unsplash.com/photo-1538485399081-7191377e8241?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d4-back",
        startTime: "22:00",
        title: "返回飯店",
        category: "hotel",
        location: "弘大飯店",
        address: "홍대입구역",
        naverQuery: "홍대입구역 호텔",
        note: "回飯店休息",
        details: ["返回飯店", "整理購物品與照片"],
        tips: ["Day 5 是地標夜景日，記得確認天氣。"],
        image: hotelRoomImage,
      },
    ],
  },
  {
    id: "day-5",
    label: "DAY 5",
    date: "2026.10.14",
    tabDate: "10.14",
    weekday: "Wed",
    title: "首爾地標夜景日",
    area: "樂天塔",
    theme: "星空圖書館 → 石村湖 → 樂天塔 → N首爾塔",
    items: [
      {
        id: "d5-start",
        startTime: "09:00",
        title: "飯店出發",
        category: "hotel",
        location: "弘大飯店",
        address: "홍대입구역",
        naverQuery: "홍대입구역 호텔",
        note: "前往 COEX 與江南方向",
        details: ["09:00 從飯店出發", "前往星空圖書館"],
        tips: ["今天移動距離較長，交通時間要預留。"],
        image: hotelRoomImage,
      },
      {
        id: "d5-library",
        startTime: "10:00",
        endTime: "12:00",
        title: "星空圖書館",
        category: "photo",
        location: "Starfield Library",
        address: "서울 강남구 영동대로 513 스타필드 코엑스몰",
        naverQuery: "별마당도서관",
        note: "巨型書牆、COEX Mall",
        details: ["巨型書牆", "COEX Mall", "室內拍照"],
        tips: ["人多時等一下空檔再拍全景。", "室內光線穩定，適合當雨天備案。"],
        image:
          "https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d5-coex-lunch",
        startTime: "12:00",
        endTime: "14:00",
        title: "COEX 午餐",
        category: "food",
        location: "COEX Mall",
        address: "서울 강남구 영동대로 513",
        naverQuery: "코엑스몰 맛집",
        note: "商場內午餐與休息",
        details: ["COEX Mall 午餐", "補充體力", "準備前往石村湖"],
        tips: ["商場選擇多，可依現場排隊狀況決定。"],
        image:
          "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d5-seokchon",
        startTime: "14:00",
        endTime: "17:00",
        title: "石村湖",
        category: "photo",
        location: "Seokchon Lake",
        address: "서울 송파구 잠실동",
        naverQuery: "석촌호수",
        note: "湖景倒影、散步拍照",
        details: ["湖景倒影", "散步拍照", "樂天塔周邊取景"],
        tips: ["湖邊風大時注意保暖。", "可把樂天世界塔納入背景構圖。"],
        image:
          "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d5-lotte-tower",
        startTime: "15:30",
        endTime: "17:00",
        title: "樂天世界塔",
        category: "photo",
        location: "Lotte World Tower",
        address: "서울 송파구 올림픽로 300",
        naverQuery: "롯데월드타워",
        note: "首爾地標、天際線",
        details: ["首爾地標", "天際線", "可與石村湖行程合併拍攝"],
        tips: ["這段與石村湖可彈性穿插，不必硬切時間。"],
        image:
          "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d5-nseoul",
        startTime: "17:00",
        endTime: "21:00",
        title: "N首爾塔",
        category: "photo",
        location: "N Seoul Tower",
        address: "서울 용산구 남산공원길 105",
        naverQuery: "N서울타워",
        note: "夕陽、藍調時刻、首爾夜景",
        details: ["夕陽", "藍調時刻", "首爾夜景"],
        tips: ["日落時間前抵達比較穩。", "夜景點風大，帶薄外套。"],
        image:
          "https://images.unsplash.com/photo-1538485399081-7191377e8241?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d5-back",
        startTime: "21:00",
        endTime: "22:00",
        title: "返回飯店",
        category: "hotel",
        location: "弘大飯店",
        address: "홍대입구역",
        naverQuery: "홍대입구역 호텔",
        note: "回飯店休息",
        details: ["返回飯店", "整理最後一天需要的行李"],
        tips: ["隔天退房，晚上先整理行李會比較不慌。"],
        image: hotelRoomImage,
      },
    ],
  },
  {
    id: "day-6",
    label: "DAY 6",
    date: "2026.10.15",
    tabDate: "10.15",
    weekday: "Thu",
    title: "最後一天輕鬆收尾",
    area: "明洞",
    theme: "汝矣島 → 明洞 → 金浦機場",
    items: [
      {
        id: "d6-checkout",
        startTime: "09:00",
        title: "飯店退房",
        category: "hotel",
        location: "弘大飯店",
        address: "弘大 Hongdae",
        naverQuery: "홍대입구역 호텔",
        note: "行李寄放飯店",
        details: ["飯店退房", "行李寄放飯店", "確認護照與機票"],
        tips: ["退房前檢查插座、浴室、床邊。", "把回程機票與護照放在最容易拿的位置。"],
        image: hotelRoomImage,
      },
      {
        id: "d6-yeouido",
        startTime: "09:30",
        endTime: "12:30",
        title: "汝矣島漢江公園",
        category: "photo",
        location: "Yeouido Hangang Park",
        address: "서울 영등포구 여의동로 330",
        naverQuery: "여의도 한강공원",
        note: "漢江、首爾城市天際線、最後一組旅行照片",
        details: ["漢江", "首爾城市天際線", "最後一組旅行照片"],
        tips: ["如果天氣不好，這段可改成室內咖啡廳或明洞提早購物。"],
        image:
          "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d6-myeongdong",
        startTime: "12:30",
        endTime: "15:30",
        title: "明洞",
        category: "shopping",
        location: "Myeong-dong",
        address: "서울 중구 명동",
        naverQuery: "명동",
        note: "最後購物、藥妝補貨、伴手禮；午餐於明洞",
        details: ["最後購物", "藥妝補貨", "伴手禮採買", "午餐於明洞"],
        tips: ["最後一天購物要注意行李重量。", "液體類商品確認能否托運。"],
        image:
          "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d6-luggage",
        startTime: "15:30",
        title: "返回飯店領取行李",
        category: "hotel",
        location: "弘大飯店",
        address: "홍대입구역",
        naverQuery: "홍대입구역 호텔",
        note: "取行李，準備前往金浦機場",
        details: ["返回飯店", "領取寄放行李", "確認所有購物品與證件"],
        tips: ["出發去機場前先秤行李或粗估重量。"],
        image: hotelRoomImage,
      },
      {
        id: "d6-gmp-transit",
        startTime: "16:00",
        title: "出發前往金浦機場",
        category: "transit",
        location: "AREX / 金浦機場",
        address: "김포국제공항",
        naverQuery: "김포국제공항",
        note: "從弘大前往金浦機場",
        details: ["16:00 出發前往金浦機場", "預留搭車與機場作業時間"],
        tips: ["回程不要壓太晚，寧可早到機場。"],
        image: airportRailroadImage,
      },
      {
        id: "d6-arrive-gmp",
        startTime: "17:00",
        title: "抵達金浦機場",
        category: "flight",
        location: "Gimpo Airport",
        address: "김포국제공항",
        naverQuery: "김포국제공항",
        note: "辦理報到、托運、安檢",
        details: ["17:00 左右抵達金浦機場", "辦理回程報到", "托運與安檢"],
        tips: ["確認免稅品、退稅、托運規定。"],
        image:
          "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?q=80&w=900&auto=format&fit=crop",
      },
      {
        id: "d6-flight-home",
        startTime: "20:35",
        title: "金浦機場起飛",
        category: "flight",
        location: "GMP → KHH",
        address: "김포국제공항",
        naverQuery: "김포국제공항",
        note: "Tigerair Taiwan IT662",
        details: ["20:35 金浦機場起飛", "返回高雄"],
        tips: ["登機前確認護照、登機證、手機。"],
        image: kaohsiungAirportImage,
      },
      {
        id: "d6-arrive-khh",
        startTime: "22:00",
        title: "抵達小港機場",
        category: "flight",
        location: "高雄國際機場",
        address: "高雄國際機場",
        naverQuery: "高雄國際機場",
        note: "結束首爾自由行",
        details: ["22:00 左右抵達小港機場", "領行李與返家"],
        tips: ["回家後再整理照片，不要在機場趕著處理。"],
        image: kaohsiungAirportImage,
      },
    ],
  },
];
